<a href="https://colab.research.google.com/github/JakeLee92/Pre-ceding/blob/master/HMNS_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


In [ ]:
print(tf.__version__)

2.3.0


In [ ]:
!nvidia-smi

Thu Aug  6 01:40:54 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   33C    P8    26W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.18.5


In [ ]:
a = [1,2,3]

In [ ]:
np_tensor = np.array(12)

In [ ]:
np_tensor

array(12)

In [ ]:
np_tensor.ndim

0

In [ ]:
np_tensor.shape

()

In [ ]:
np_tensor.size

1

In [ ]:
np_tensor.dtype

dtype('int64')

In [ ]:
tensor_1d = np.array([1,2,3,4,5])

In [ ]:
tensor_1d

array([1, 2, 3, 4, 5])

In [ ]:
tensor_1d.ndim tensor_1d.shape tensor_1d.dtype

SyntaxError: ignored

In [15]:
tensor_2d = np.array([[7,2],[51,12],[41,22]])





In [16]:
tensor_2d.shape

(3, 2)

In [23]:
tensor_3d = np.array([[[7,2],[51,12],[21 ,3]],[[7,2],[51,12],[21 ,3]]])

In [24]:
tensor_3d.shape

(2, 3, 2)

In [28]:
tensor_3_1d = np.array([[[7],[12],[3]],[[2],[12],[3]]])

In [29]:
tensor_3_1d.shape

(2, 3, 1)

In [30]:
tensor_3d.reshape((6,2))

array([[ 7,  2],
       [51, 12],
       [21,  3],
       [ 7,  2],
       [51, 12],
       [21,  3]])

In [31]:
tensor_3d

array([[[ 7,  2],
        [51, 12],
        [21,  3]],

       [[ 7,  2],
        [51, 12],
        [21,  3]]])

In [33]:
tensor_4d = tensor_3d.reshape((2,3,2,1))

In [34]:
print(tensor_4d.ndim, tensor_4d.shape, tensor_4d.size, tensor_4d.dtype)

4 (2, 3, 2, 1) 12 int64
